[package]
name = "wasm-bus-tty"
version = "1.2.1"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "WebAssembly Terminal Interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "websocket" ]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"

[features]
default = []
sys = [ "libc" ]

[dependencies]
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
url = "2"
async-trait = "^0.1"
wasm-bus = { version = "^1", path = "../lib", default_features = false, features = [ "rt", "macros" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "^1", features = [ "sync", "macros" ], default_features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libc = { version = "0.2", optional = true }
tokio = { version = "^1", features = [ "io-util", "io-std", "macros", "sync", "fs" ], default_features = false }

[dev-dependencies]
tokio = { version = "^1", features = [ "rt", "rt-multi-thread", "io-util", "io-std", "macros", "sync", "fs" ], default_features = false }