[package]
name = "wasmer-bus-time"
version = "1.1.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly Time Interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "time" ]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"

[features]
default = []

[dependencies]
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "rt", "macros" ] }
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
tokio = { version = "^1", features = [ "sync", "macros", "time" ], default_features = false }
async-trait = "^0.1"
