[package]
name = "wasm-bus-mio"
version = "1.0.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly MIO"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "opengl", "webgl" ]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"

[features]
default = [ "quantum", "sys" ]
quantum = [ "ate-crypto/quantum", "ate-comms/quantum" ]
sys = [ "ate-comms/sys", "ate-comms/dns", "wasm-bus/sys" ]

[dependencies]
tracing = { version = "^0.1", features = [ "log" ] }
ate-crypto = { version = "^1", path = "../../crypto", default_features = false }
ate-comms = { version = "^1", path = "../../comms", default_features = false }
wasm-bus = { version = "^1", path = "../lib", default_features = false, features = [ "rt", "macros" ] }
wasm-bus-ws = { version = "^1", path = "../ws" }
wasm-bus-time = { version = "^1", path = "../time" }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
url = "^2"
hex = "^0.4"
bincode = "^1"
fastrand = "^1"
base64 = "^0.13"
shellexpand = "^2"
chrono = { version = "^0.4", git = "https://github.com/john-sharratt/chrono.git", features = ["serde"] }
derivative = { version = "^2" }
tokio = { version = "^1", features = [ "macros", "sync" ], default_features = false }

[dev-dependencies]
clap = { version = "^3.0.0-rc.7", features = [ "derive" ] }
fastrand = "^1.4"
byteorder = "^1.4"