[package]
name = "wasmer-bus-deploy"
version = "1.0.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2021"
description = "WebAssembly fuse bus interface"
license = "MIT OR Apache-2.0"
keywords = [ "wasi", "wasm", "bus", "fuse" ]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"

[features]
default = []
backend = []

[dependencies]
wasmer-bus = { version = "^1", path = "../lib", default_features = false, features = [ "macros" ] }
tracing = { version = "^0.1", features = [ "log" ] }
serde = { version = "^1", features = ["derive"] }
tokio = { version = "1", features = [ "sync", "macros" ], default_features = false }
async-trait = "^0.1"

[dev-dependencies]
tracing = { version = "^0.1", features = [ "log" ] }
tracing-futures = { version = "^0.2" }
tracing-subscriber = { version = "^0.2" }